# Package Overview
package_name: plant_leave_diseases_model

# Data Files
train_path: train
validation_path: validation
test_path: test

dataset_url: "https://prod-dcd-datasets-public-files-eu-west-1.s3.eu-west-1.amazonaws.com/349ac012-2948-4172-bbba-3bf8f76596fd"
dataset_data_dir: "Plant_leave_diseases_dataset_with_augmentation"
dataset_class_dir: "datasets/classes"
dataset_class_file: "plant_leave_diseases_classes.txt"


model_name: plant_leave_diseases_model
model_save_file: plant_leave_diseases_model_output_v

# Feature engineering parameters
image_size: 
  - 256
  - 256
batch_size: 5
scaling_factor: 255.0
rotation: 0.1
zoom: 0.2
flip: horizontal

# Set the random seed
random_state: 42

# Alogrithm parameters
input_shape: 
  - 256
  - 256
  - 3
epochs: 1
optimizer: adam
loss: categorical_crossentropy
accuracy_metric: accuracy
verbose: 1
earlystop: 0
monitor: val_loss
save_best_only: True

learning_rate: 0.0001

# Mappings for calss labels
label_mappings: 
  0: cat
  1: dog

no_of_classes: 5
no_of_img_per_class_test: 5
no_of_img_per_class_train: 5
no_of_img_per_class_val: 5